services:
  router:
    container_name: router
    image: mongo
    command: mongos --configdb config/config1:27017,config2:27017,config3:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 12501:27017
    networks:
      - mongo

networks:
  mongo:
    name: mongo
    external: true
